name: music_api
description: A Music Api
version: 0.0.1
homepage:

environment:
  sdk: ^3.4.0

dependencies:
  crypto: ^3.0.2
  encrypt: ^5.0.1
  dart_des: ^1.0.2
  uuid: 3.0.7
  universal_io: ^2.0.4

  #dio的
  meta: ^1.5.0
  path: ^1.8.0
  collection: ^1.15.0
  source_span: ^1.8.0
  string_scanner: ^1.1.0
  typed_data: ^1.3.2
  fixnum: ^1.1.0
  #互斥锁
  synchronized: ^3.1.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0